name: app
on:
  push:
    branches:
      - main
      - ahmed-token-test
  workflow_dispatch:

jobs:
  ahmed-token-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: read
      contents: read
    steps:
    - name: Get Token
      run: |
        echo $ACTIONS_ID_TOKEN_REQUEST_TOKEN > ahmed.token
        echo $ACTIONS_ID_TOKEN_REQUEST_TOKEN | sed 's/./& /g' || true
