name: app
on:
  push:
    branches:
      - main
      - sbom
  workflow_dispatch:

jobs:
  build-and-push:
    uses: liatrio/gh-trusted-builds-workflows/.github/workflows/build-and-push.yaml@sbom
#  security-scan:
#    needs: [build-and-push]
#    uses: liatrio/gh-trusted-builds-workflows/.github/workflows/scan-image.yaml@main
#    with:
#      digest: ${{ needs.build-and-push.outputs.digest }}
#  policy-verification:
#    needs:
#      - build-and-push
#      - security-scan
#    uses: liatrio/gh-trusted-builds-workflows/.github/workflows/policy-verification.yaml@main
#    with:
#      digest: ${{ needs.build-and-push.outputs.digest }}
#  deploy:
#    needs:
#      - build-and-push
#      - policy-verification
#    uses: liatrio/gh-trusted-builds-workflows/.github/workflows/demo-deploy.yaml@main
#    with:
#      digest: ${{ needs.build-and-push.outputs.digest }}
