name: app
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    uses: liatrio/gh-trusted-builds-workflows/.github/workflows/build-and-push.yaml@v1.1.2
  security-scan:
    needs: [build-and-push]
    uses: liatrio/gh-trusted-builds-workflows/.github/workflows/scan-image.yaml@v1.1.2
    with:
      digest: ${{ needs.build-and-push.outputs.digest }}
  policy-verification:
    needs:
      - build-and-push
      - security-scan
    uses: liatrio/gh-trusted-builds-workflows/.github/workflows/policy-verification.yaml@v1.1.2
    with:
      digest: ${{ needs.build-and-push.outputs.digest }}
  deploy:
    needs:
      - build-and-push
      - policy-verification
    uses: liatrio/gh-trusted-builds-workflows/.github/workflows/demo-deploy.yaml@v1.1.2
    with:
      digest: ${{ needs.build-and-push.outputs.digest }}
