name: app
on:
  push:
    branches:
      - main
      - update-cosign
  workflow_dispatch:

jobs:
  build-and-push:
    uses: liatrio/gh-trusted-builds-workflows/.github/workflows/build-and-push.yaml@update-cosign
    permissions:
      actions: read
      id-token: write
      contents: read
      packages: write
      pull-requests: read
  security-scan:
    needs: [ build-and-push ]
    uses: liatrio/gh-trusted-builds-workflows/.github/workflows/scan-image.yaml@update-cosign
    permissions:
      id-token: write
      contents: read
      packages: write
    with:
      digest: ${{ needs.build-and-push.outputs.digest }}
  policy-verification:
    needs:
      - build-and-push
      - security-scan
    uses: liatrio/gh-trusted-builds-workflows/.github/workflows/policy-verification.yaml@update-cosign
    permissions:
      id-token: write
      contents: read
      packages: write
    with:
      digest: ${{ needs.build-and-push.outputs.digest }}
  deploy:
    needs:
      - build-and-push
      - policy-verification
    uses: liatrio/gh-trusted-builds-workflows/.github/workflows/demo-deploy.yaml@update-cosign
    permissions:
      id-token: write
      packages: read
      contents: read
    with:
      digest: ${{ needs.build-and-push.outputs.digest }}
